language: node_js
node_js:
  - 'stable'

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run coverage
after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
